# Generated by Django 3.1.2 on 2021-05-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
